
mfig = figure; % open figure window
figp = uipanel('Title','Main Panel','FontSize',10,...
             'BackgroundColor','white',...
             'Position',[.05 .05 .9 .2]);
pos = getpixelposition(figp); %// gives x left, y bottom, width, height
ishghandle(mfig)
posshift= (pos(1) + (pos(3)-pos(1))/3)
figsubpb1 = uicontrol('Parent',figp,'String','nr1',...
    'Position',[pos(1) 18 72 36]); %'Position',[1.8*(outrow*5) 18 72 36])
figsubpb2 = uicontrol('Parent',figp,'String','nr2',...
    'Position',[posshift 18 72 36]); %'Position',[1.8*(outrow*5) 18 72 36])
figsubpb3 = uicontrol('Parent',figp,'String','nr3',...
    'Position',[posshift*2 18 72 36]); %'Position',[1.8*(outrow*5) 18 72 36])